# This file was generated by GoReleaser. DO NOT EDIT.
cask "mkdown" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "139450f3847701cbbee352cb6d47dbde6045bc5992b03cb3b18170f1e24c764d"
      url "https://github.com/ekinertac/mkdown/releases/download/v#{version}/mkdown_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4a46efe6534a4500ae75ddfba86c71144b17e63f9d1e69699ec76b8bb20895d9"
      url "https://github.com/ekinertac/mkdown/releases/download/v#{version}/mkdown_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0e83b2b56a50d1be3a3ff3474625c920c9344a8ab5047af51dc4f5a2a77034ef"
      url "https://github.com/ekinertac/mkdown/releases/download/v#{version}/mkdown_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "69e560ed666cc412f5d4fffa48b998cb09d452ae582aea41570682680276fe4f"
      url "https://github.com/ekinertac/mkdown/releases/download/v#{version}/mkdown_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mkdown"
  desc "Fast single-binary markdown to HTML converter"
  homepage "https://github.com/ekinertac/mkdown"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mkdown"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mkdown"]
    end
  end

  # No zap stanza required

end
