# This file was generated by GoReleaser. DO NOT EDIT.
cask "mkdown" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "6a2433dc2fc4b76bbfab69211a4d046d7280e015563040ebf766e70bce7920c7"
      url "https://github.com/ekinertac/mkdown/releases/download/v#{version}/mkdown_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5075b34694ef11ac756032c569cba00f1a5d2de2c94fe3feab1b3bff5066dac8"
      url "https://github.com/ekinertac/mkdown/releases/download/v#{version}/mkdown_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ceb6b8aa60172f109e9a9af799c7e6ef2a3d2c87187ceb1aeac34e5f2833a801"
      url "https://github.com/ekinertac/mkdown/releases/download/v#{version}/mkdown_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "63d8bdbb267453910ec6645c43e3aaa5b8a22ea4f6eb9e96071ba3bba65400d9"
      url "https://github.com/ekinertac/mkdown/releases/download/v#{version}/mkdown_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mkdown"
  desc "Fast single-binary markdown to HTML converter"
  homepage "https://github.com/ekinertac/mkdown"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mkdown"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mkdown"]
    end
  end

  # No zap stanza required

end
