# This file was generated by GoReleaser. DO NOT EDIT.
cask "mkdown" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "0cb2a077d20957128da97d9f8c973dc2a5dd60b537d3d8cce02d544ae0238fd5"
      url "https://github.com/ekinertac/mkdown/releases/download/v#{version}/mkdown_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "41ad214adc32e8c2d9d6b34f558efeae59d171ec5ce3158149e58c90d5fd03ea"
      url "https://github.com/ekinertac/mkdown/releases/download/v#{version}/mkdown_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0b5ba396f6df6b7e919aeab3bf8ff52ba43f5d12e0f8203d069bb229cf2d293a"
      url "https://github.com/ekinertac/mkdown/releases/download/v#{version}/mkdown_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f03335a6b817e6e9ca81b2262e83c62a18a50a48c5f7b15ba4a16cd06654c616"
      url "https://github.com/ekinertac/mkdown/releases/download/v#{version}/mkdown_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mkdown"
  desc "Fast single-binary markdown to HTML converter"
  homepage "https://github.com/ekinertac/mkdown"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mkdown"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mkdown"]
    end
  end

  # No zap stanza required

end
