# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnemo" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "011e49f8770db6d1a59c19e95fd18bfc2e484222d8e0491733d20efef30b7184"
      url "https://github.com/ekinertac/mnemo/releases/download/v#{version}/mnemo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b90ddeaf8a34ca30657d23d5cb2456fca9e6d9bf447686656567ea22bbe514ff"
      url "https://github.com/ekinertac/mnemo/releases/download/v#{version}/mnemo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e0ace6e2e5c8346356398e4a8d1fd801db5d16394ab2c431181786188bf6ce86"
      url "https://github.com/ekinertac/mnemo/releases/download/v#{version}/mnemo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1622daa0ab72e4b50b241ea87aaee3dca2f9544a01424fc56a53a72c48d28427"
      url "https://github.com/ekinertac/mnemo/releases/download/v#{version}/mnemo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mnemo"
  desc "Sync Claude Code sessions across machines as encrypted, deduplicated, append-only restic snapshots"
  homepage "https://github.com/ekinertac/mnemo"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "restic",
    ]

  binary "mnemo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mnemo"]
    end
  end

  # No zap stanza required

end
