# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnemo" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "f12d8eeddd6d14024970a29ead05314567d018420ecf4d0045332a207362c040"
      url "https://github.com/ekinertac/mnemo/releases/download/v#{version}/mnemo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5fb27cdfe09deef8c922d2c7b5a8593a29f17c6375fda2448822c540ad2fb7e5"
      url "https://github.com/ekinertac/mnemo/releases/download/v#{version}/mnemo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ded96a82018c2d47f2fd2da5fa14d0861c16afeb1084e35a912f14fe9d291444"
      url "https://github.com/ekinertac/mnemo/releases/download/v#{version}/mnemo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "548757852f03620ad6a46b1777ef65729846e1cd3fd2ce0bdac7c3105c13c526"
      url "https://github.com/ekinertac/mnemo/releases/download/v#{version}/mnemo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mnemo"
  desc "Sync Claude Code sessions across machines as encrypted, deduplicated, append-only restic snapshots"
  homepage "https://github.com/ekinertac/mnemo"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
      "restic",
    ]

  binary "mnemo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mnemo"]
    end
  end

  # No zap stanza required

end
