# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnemo" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "6b4a95f7b9de04d3f3e20cf9cd34e8b091d498fee47240222d0bb140a7c319aa"
      url "https://github.com/ekinertac/mnemo/releases/download/v#{version}/mnemo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "178c6fab45d4b52944bfdb5323cc02cb01a0d0c09df0fcec6af9a4fe5928ee2d"
      url "https://github.com/ekinertac/mnemo/releases/download/v#{version}/mnemo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d5b719010b79f821b5a7c9cec9ece69d8b9baed4a88826417be86baa36565d8d"
      url "https://github.com/ekinertac/mnemo/releases/download/v#{version}/mnemo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "04574f8e70c256e212f7ff9701c123f371106fcfd722d171ae63d1888433b84c"
      url "https://github.com/ekinertac/mnemo/releases/download/v#{version}/mnemo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mnemo"
  desc "Sync Claude Code sessions across machines as encrypted, deduplicated, append-only restic snapshots"
  homepage "https://github.com/ekinertac/mnemo"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "restic",
    ]

  binary "mnemo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mnemo"]
    end
  end

  # No zap stanza required

end
